print("Введите число:")
a=int(input())
print("Введите число:")
b=int(input())
print("Введите число:")
c=int(input())
print("Сумма введенных чисел:" , a+b+c)
print("Произведение введенных чисел:" , a*b*c)
